name:
  maximum: 50
email:
  maximum: 255
password:
  minimum: 6
image:
  size: 80
avatar_index_page:
  size: 50
paginate:
  size: 10
hours_expired:
  time: 2
content:
  max_length: 140
picture_size:
  capacity_value: 1
  size_value: 400

